name: Deploy portfolio

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download source
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build -- --base=/nayoungportfolio07/

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Upload website
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

      - name: Publish website
        id: deployment
        uses: actions/deploy-pages@v5
